language: node_js

node_js:
  - "6"

before_script:
  - mkdir build/logs
  - npm install -g istanbul
  - npm install -g codeclimate-test-reporter

script:
  - npm run-script travis

after_success:
  - codeclimate-test-reporter < build/logs/lcov.info

notifications:
  email: "bianco@javanile.org"
